[package]
name = "rustop"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.98"
chrono = "0.4.41"
clap = { version = "4.5.41", features = ["derive"] }
ratatui = "0.29.0"
users = "0.11.0"
